### ISSUE TITLE
Fetch publication's post 

### ISSUE THREAD

**Issue by srsandy** [Medium/medium-api-docs#121] opened 2018-03-09 04:31 UTC
Can you pls tell me a way to Fetch the publication all post's

**Comment by brunopulis** [comment] 2018-06-29 20:21
Hello, @srsandy , Medium does not have an endpoint to search for the /GET requests. What can be done is to use RSS to search for posts. Like this: `https://medium.com/feed/@youruser`

**Comment by srsandy** [comment] 2018-07-02 07:01
Thanks @brunopulis :)

**Comment by SarasArya** [comment] 2018-07-09 17:14
Hi @brunopulis Even if I comment it becomes a story in Medium. Any way I can remove those?

**Comment by brunopulis** [comment] 2018-07-12 03:19
Hi @SarasArya hmm, i will search about this.

**Comment by MediumEng** [comment] 2018-10-11 02:19
Clsoing as duplicate of https://github.com/Medium/medium-api-docs/issues/118

**Closed by MediumEng** 2018-10-11 02:19 UTC
