### ISSUE TITLE
Can't open authorization url

### ISSUE THREAD

**Issue by s0nskar** [Medium/medium-api-docs#62] opened 2016-07-09 19:52 UTC
I tried to open my authorization url i.e `https://medium.com/m/oauth/authorize?client_id=removed-my-client_id-for-safty&scope=basicProfile%2CpublishPost&response_type=code&state=secretState&redirect_uri=https%3A%2F%2Ftechnex.in%2Fcallback` but i am getting a 400 : We didn’t understand your request.
Help me

**Comment by grokify** [comment] 2016-08-12 06:55
A 400 error means one of your parameters is wrong. I tried with the same parameter names and it worked for me, though I did encounter some 400s during my testing.

A quick way to test is using the [OAuth 2.0 demo app](https://github.com/grokify/medium-sdk-ruby/tree/master/scripts/sinatra) in this [Ruby SDK](https://github.com/grokify/medium-sdk-ruby) I just put together.

**Comment by arunthampi** [comment] 2017-01-07 01:32
@grokify getting the same errors as @s0nskar. I tried using your Gemfile, generated `authorize_uri` using `client.connection.authorize_uri`, pasted in the browser and I get a 400 request.

Confirmed that the callback URL is set correctly while registering the application.

Any ideas? Much appreciated

**Comment by olgageletina** [comment] 2017-01-18 03:07
@arunthampi Any luck? Experiencing the same issue as well

**Comment by arunthampi** [comment] 2017-01-18 18:11
@olgageletina it started working after the weekend -- I wonder if there is some behind-the-scenes approval process going on. Any medium staff around that can confirm this?

**Comment by kylewm** [comment] 2017-01-19 01:57
There isn't a manual approval process for apps (other than those that need extended permissions). Closing since the issue appears to have been a transient bug that is now resolved (hopefully!)

**Closed by kylewm** 2017-01-19 01:57 UTC

**Comment by geodeveloper** [comment] 2017-02-01 15:56
I'm experiencing same issue too. I've checked and re-checked all params being sent to `https://medium.com/m/oauth/authorize` and seems to be okay, but a 400 response is returned.
